branches:
  only:
    - master

sudo: required

os:
  - linux

osx_image: xcode8.2

language: generic

env:
- PY=2.7
- PY=3.4


addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gfortran
    - libblas-dev
    - liblapack-dev
    - libopenmpi-dev
    - openmpi-bin
    - gcc-5
    - g++-5

install:
- pip install --upgrade pip
- pip install numpy scipy nose Cython
- pip install git+https://github.com/OpenMDAO/testflo.git
- pip install -e .

script:
- testflo
- cd doc
- cd Sphinx_doc
- make html
