branches:
  only:
    - master

sudo: required

os:
  - linux
  - osx

osx_image: xcode8.2

language: generic

env:
- PY=2.7

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gfortran
    - libblas-dev
    - liblapack-dev
    - libopenmpi-dev
    - openmpi-bin
    - gcc-5
    - g++-5

install:
- pip3 install --upgrade pip
- sudo pip3 install numpy scipy Cython
- sudo pip3 install git+https://github.com/OpenMDAO/testflo.git
- sudo pip3 install git+https://github.com/hwangjt/sphinx_auto_embed.git
- sudo pip3 install -e .

script:
- testflo
- cd doc
- sphinx_auto_embed
- make html
