branches:
  only:
    - master

sudo: required

os:
  - linux
  - osx

osx_image: xcode7.3

language: generic

env:
- PY=2.7
- PY=3.6 COVERAGE=1

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gfortran
    - libblas-dev
    - liblapack-dev
    - libopenmpi-dev
    - openmpi-bin
    - gcc-5
    - g++-5

install:
- pip install --upgrade pip
- pip install numpy scipy cython
- pip install git+https://github.com/OpenMDAO/testflo.git
- pip install git+https://github.com/hwangjt/sphinx_auto_embed.git
- pip install -e . --ignore-installed six
- pip install coverage;
- pip install coveralls-python

script:
- testflo -n 1 smt --verbose --coverage --coverpkg=smt  
- cd doc
- sphinx_auto_embed
- make html

after_success:
# again, only run coverage operations on the upload machine after success.
- if [ "$COVERAGE" ]; then
    coveralls
  fi
