build: false
version: 0.3.{build}
platform:
  - x64

environment:
  matrix:
    - PYTHON: 2.7
      CONDA: "C:\\Miniconda-x64"
    - PYTHON: 3.6
      CONDA: "C:\\Miniconda36-x64"
#    - PYTHON: 3.7
#      CONDA: "C:\\Miniconda37-x64"

install:
  - set PATH=%CONDA%;%CONDA%\Scripts;%PATH%
  - conda config --set always_yes yes
  - conda update conda
  - if %PYTHON%==2.7 (
      conda install python=%PYTHON% Cython sphinx pip --quiet
    ) else (
      conda install python=%PYTHON% numpy scipy Cython sphinx pip --quiet
    )
  - pip install numpy
  - pip install testflo
  - pip install git+https://github.com/hwangjt/sphinx_auto_embed.git
  - pip install -e . 
  - pip list
  - conda list

test_script:
  - testflo . -n 1
  - cd doc
  - sphinx_auto_embed
  - make html
